import { useCallback, useEffect, useMemo, useState } from "react";
import { Dialog, DialogPanel, DialogTitle } from "@headlessui/react";
import { MagnifyingGlassIcon, PencilSquareIcon, PlusIcon, TrashIcon, XMarkIcon } from "@heroicons/react/24/outline";
import { toast } from "sonner";
import { useOutletContext } from "react-router";
import api from "../../shared/api/client";

export default function CatalogPage({title,subtitle,endpoint,secondaryEndpoint,kind}){
 const{companyId,companies}=useOutletContext();const[currentEndpoint,setCurrentEndpoint]=useState(endpoint);const[rows,setRows]=useState([]);const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);const[modal,setModal]=useState(null);
 useEffect(()=>setCurrentEndpoint(endpoint),[endpoint]);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get(currentEndpoint,{params:{busca:search,size:50}});setRows(r.data.content||[])}catch(e){toast.error(e.userMessage)}finally{setLoading(false)}},[currentEndpoint,search]);useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);
 const columns=useMemo(()=>kind==='employee'?[['codigo','Código'],['nome','Nome'],['email','E-mail'],['empresaNome','Empresa']]:kind==='user'?[['login','Login'],['nome','Nome'],['perfil','Perfil'],['empresaNome','Empresa']]:[['codigo','Código'],['nome','Nome'],['descricao','Descrição'],...(kind==='company'?[]:[['empresaNome','Empresa']])],[kind]);
 async function remove(row){if(!confirm(`Excluir ${row.nome}?`))return;try{await api.delete(`${currentEndpoint}/${row.id}`);toast.success('Registro excluído');load()}catch(e){toast.error(e.userMessage)}}
 return <div className="page"><div className="page-title"><div><p className="eyebrow">Cadastro e gestão</p><h1>{title}</h1><p>{subtitle}</p></div><button className="primary" onClick={()=>setModal({})}><PlusIcon/>Novo registro</button></div>{secondaryEndpoint&&<div className="tabs"><button className={currentEndpoint===endpoint?'active':''} onClick={()=>setCurrentEndpoint(endpoint)}>Interno</button><button className={currentEndpoint===secondaryEndpoint?'active':''} onClick={()=>setCurrentEndpoint(secondaryEndpoint)}>Externo</button></div>}<section className="panel table-panel"><div className="table-toolbar"><div className="search-box"><MagnifyingGlassIcon/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome…"/></div><span>{rows.length} registros</span></div><div className="table-wrap"><table><thead><tr>{columns.map(([,label])=><th key={label}>{label}</th>)}<th className="actions">Ações</th></tr></thead><tbody>{loading?[...Array(4)].map((_,i)=><tr key={i} className="skeleton-row">{[...columns,[]].map((_,j)=><td key={j}><span/></td>)}</tr>):rows.length?rows.map(row=><tr key={row.id}>{columns.map(([key])=><td key={key}>{key==='perfil'?<span className="badge">{row[key]}</span>:row[key]||'—'}</td>)}<td className="actions"><button className="icon" onClick={()=>setModal(row)} aria-label="Editar"><PencilSquareIcon/></button><button className="icon danger" onClick={()=>remove(row)} aria-label="Excluir"><TrashIcon/></button></td></tr>):<tr><td colSpan={columns.length+1}><div className="empty-inline"><strong>Nenhum registro encontrado</strong><span>Crie o primeiro item ou ajuste a busca.</span></div></td></tr>}</tbody></table></div></section><CatalogDialog open={modal!==null} value={modal||{}} onClose={()=>setModal(null)} kind={kind} companies={companies} companyId={companyId} endpoint={currentEndpoint} onSaved={()=>{setModal(null);load()}}/></div>
}

function CatalogDialog({open,value,onClose,kind,companies,companyId,endpoint,onSaved}){const[form,setForm]=useState({});const[saving,setSaving]=useState(false);useEffect(()=>setForm({...value,empresaId:value.empresaId||companyId,ativo:value.ativo??true,perfil:value.perfil||'USER'}),[value,companyId,open]);const field=(name,label,type='text',required=true)=><label>{label}<input type={type} value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value})} required={required}/></label>;
 async function save(e){e.preventDefault();setSaving(true);const payload={...form};if(kind==='user'&&!payload.senha)delete payload.senha;try{value.id?await api.put(`${endpoint}/${value.id}`,payload):await api.post(endpoint,payload);toast.success(value.id?'Registro atualizado':'Registro criado');onSaved()}catch(err){toast.error(err.userMessage)}finally{setSaving(false)}}
 return <Dialog open={open} onClose={onClose} className="dialog"><div className="dialog-backdrop"/><div className="dialog-shell"><DialogPanel className="dialog-panel"><div className="dialog-title"><div><p className="eyebrow">{value.id?'Edição':'Novo cadastro'}</p><DialogTitle>{value.nome||'Preencha os dados'}</DialogTitle></div><button className="icon" onClick={onClose}><XMarkIcon/></button></div><form onSubmit={save}><div className="form-grid">{kind==='user'?<>{field('login','Login')}{field('nome','Nome')}{field('senha',value.id?'Nova senha (opcional)':'Senha','password',!value.id)}<label>Perfil<select value={form.perfil||'USER'} onChange={e=>setForm({...form,perfil:e.target.value})}><option>USER</option><option>ADMIN</option></select></label></>:<>{field('codigo','Código')}{field('nome','Nome')}{kind==='employee'&&field('email','E-mail','email')}<label className="full">Descrição<textarea value={form.descricao||''} onChange={e=>setForm({...form,descricao:e.target.value})}/></label></>}{kind!=='company'&&<label className="full">Empresa<select value={form.empresaId||''} onChange={e=>setForm({...form,empresaId:e.target.value})} required><option value="">Selecione</option>{companies.map(c=><option value={c.id} key={c.id}>{c.nome}</option>)}</select></label>}</div><div className="dialog-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando…':'Salvar'}</button></div></form></DialogPanel></div></Dialog>}
