import { useCallback, useEffect, useRef, useState } from "react";
import { Dialog, DialogPanel, DialogTitle } from "@headlessui/react";
import { ChevronDownIcon, ChevronRightIcon, MagnifyingGlassMinusIcon, MagnifyingGlassPlusIcon, PlusIcon, Squares2X2Icon, TrashIcon, XMarkIcon } from "@heroicons/react/24/outline";
import { toast } from "sonner";
import { useOutletContext } from "react-router";
import api from "../../shared/api/client";

export default function OrganizationPage(){const{companyId}=useOutletContext();const[tree,setTree]=useState([]);const[selected,setSelected]=useState(null);const[collapsed,setCollapsed]=useState(new Set());const[zoom,setZoom]=useState(1);const[offset,setOffset]=useState({x:0,y:0});const[modal,setModal]=useState(false);const[assignment,setAssignment]=useState(false);const drag=useRef(null);
 const load=useCallback(()=>{if(!companyId)return;api.get('/unidades/tree',{params:{empresaId:companyId}}).then(r=>setTree(r.data)).catch(e=>toast.error(e.userMessage))},[companyId]);useEffect(load,[load]);
 function toggle(id){setCollapsed(old=>{const n=new Set(old);n.has(id)?n.delete(id):n.add(id);return n})}function move(e){if(!drag.current)return;setOffset({x:e.clientX-drag.current.x,y:e.clientY-drag.current.y})}
 async function remove(){if(!selected||!confirm(`Excluir ${selected.nome}?`))return;try{await api.delete(`/unidades/${selected.id}`);setSelected(null);load()}catch(e){toast.error(e.userMessage)}}
 return <div className="page organogram-page"><div className="page-title"><div><p className="eyebrow">Estrutura organizacional</p><h1>Organograma</h1><p>Navegue pela hierarquia, identifique responsáveis e conecte pessoas aos processos.</p></div><button className="primary" disabled={!companyId} onClick={()=>setModal(true)}><PlusIcon/>Nova unidade</button></div><div className="org-layout"><section className="org-canvas" onPointerMove={move} onPointerUp={()=>drag.current=null} onPointerLeave={()=>drag.current=null}><div className="canvas-tools"><button className="icon" onClick={()=>setZoom(z=>Math.min(1.6,z+.15))}><MagnifyingGlassPlusIcon/></button><button className="icon" onClick={()=>setZoom(z=>Math.max(.55,z-.15))}><MagnifyingGlassMinusIcon/></button><button onClick={()=>{setZoom(1);setOffset({x:0,y:0})}}>Centralizar</button><span>{Math.round(zoom*100)}%</span></div><div className="tree-stage" onPointerDown={e=>{if(e.target.closest('.org-node'))return;drag.current={x:e.clientX-offset.x,y:e.clientY-offset.y};e.currentTarget.setPointerCapture(e.pointerId)}} style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${zoom})`}}>{tree.length?tree.map(node=><TreeNode key={node.id} node={node} selected={selected?.id} collapsed={collapsed} toggle={toggle} select={setSelected}/>):<div className="empty-state compact"><Squares2X2Icon/><h3>Nenhuma unidade</h3><p>Crie a unidade raiz desta empresa.</p></div>}</div></section><aside className="detail-panel">{selected?<><div className="detail-head"><div className="org-avatar">{selected.nome.slice(0,2).toUpperCase()}</div><div><p className="eyebrow">Unidade selecionada</p><h2>{selected.nome}</h2><span>{selected.codigo}</span></div></div><p className="detail-description">{selected.descricao||'Sem descrição cadastrada.'}</p><div className="detail-metrics"><div><strong>{selected.funcionarios}</strong><span>Funcionários</span></div><div><strong>{selected.children?.length||0}</strong><span>Unidades filhas</span></div></div><dl><dt>Responsável</dt><dd>{selected.funcionarios?'Vínculo funcional cadastrado':'Não definido'}</dd><dt>Processos</dt><dd>Visíveis no módulo de processos</dd></dl><div className="detail-actions"><button className="primary" onClick={()=>setAssignment(true)}>Vincular funcionário</button><button onClick={()=>setModal(true)}><PlusIcon/>Criar unidade filha</button><button className="danger-text" onClick={remove}><TrashIcon/>Excluir</button></div></>:<div className="empty-state compact"><Squares2X2Icon/><h3>Selecione uma unidade</h3><p>Os detalhes e vínculos aparecerão aqui.</p></div>}</aside></div><UnitDialog open={modal} onClose={()=>setModal(false)} companyId={companyId} parent={selected} saved={()=>{setModal(false);load()}}/><AssignmentDialog open={assignment} onClose={()=>setAssignment(false)} unit={selected} companyId={companyId} saved={()=>{setAssignment(false);load()}}/></div>}

function TreeNode({node,selected,collapsed,toggle,select}){const has=node.children?.length>0;return <div className="tree-branch"><button className={`org-node ${selected===node.id?'selected':''}`} onClick={()=>select(node)}><span className="node-icon">{node.nome.slice(0,2).toUpperCase()}</span><span><b>{node.nome}</b><small>{node.funcionarios} funcionário{node.funcionarios===1?'':'s'}</small></span>{has&&<i onClick={e=>{e.stopPropagation();toggle(node.id)}}>{collapsed.has(node.id)?<ChevronRightIcon/>:<ChevronDownIcon/>}</i>}</button>{has&&!collapsed.has(node.id)&&<div className="tree-children">{node.children.map(child=><TreeNode key={child.id} node={child} selected={selected} collapsed={collapsed} toggle={toggle} select={select}/>)}</div>}</div>}

function UnitDialog({open,onClose,companyId,parent,saved}){const[form,setForm]=useState({codigo:'',nome:'',descricao:''});const[saving,setSaving]=useState(false);useEffect(()=>setForm({codigo:'',nome:'',descricao:''}),[open]);async function submit(e){e.preventDefault();setSaving(true);try{await api.post('/unidades',{...form,empresaId:companyId,parentId:parent?.id||null});toast.success('Unidade criada');saved()}catch(err){toast.error(err.userMessage)}finally{setSaving(false)}}return <Dialog open={open} onClose={onClose} className="dialog"><div className="dialog-backdrop"/><div className="dialog-shell"><DialogPanel className="dialog-panel"><div className="dialog-title"><div><p className="eyebrow">Organograma</p><DialogTitle>{parent?`Nova unidade em ${parent.nome}`:'Nova unidade raiz'}</DialogTitle></div><button className="icon" onClick={onClose}><XMarkIcon/></button></div><form onSubmit={submit}><div className="form-grid"><label>Código<input value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})} required/></label><label>Nome<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} required/></label><label className="full">Descrição<textarea value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></label></div><div className="dialog-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>Criar unidade</button></div></form></DialogPanel></div></Dialog>}

function AssignmentDialog({open,onClose,unit,companyId,saved}){const[employees,setEmployees]=useState([]);const[form,setForm]=useState({funcionarioId:'',responsavel:false,inicio:new Date().toISOString().slice(0,10)});useEffect(()=>{if(open)api.get('/funcionarios?size=100').then(r=>setEmployees(r.data.content.filter(f=>f.empresaId===companyId)))},[open,companyId]);async function submit(e){e.preventDefault();try{await api.post('/funcionario-unidades',{...form,unidadeId:unit.id});toast.success('Funcionário vinculado');saved()}catch(err){toast.error(err.userMessage)}}return <Dialog open={open} onClose={onClose} className="dialog"><div className="dialog-backdrop"/><div className="dialog-shell"><DialogPanel className="dialog-panel"><div className="dialog-title"><div><p className="eyebrow">Alocação organizacional</p><DialogTitle>Vincular a {unit?.nome}</DialogTitle></div><button className="icon" onClick={onClose}><XMarkIcon/></button></div><form onSubmit={submit}><div className="form-grid"><label className="full">Funcionário<select value={form.funcionarioId} onChange={e=>setForm({...form,funcionarioId:e.target.value})} required><option value="">Selecione</option>{employees.map(f=><option key={f.id} value={f.id}>{f.nome}</option>)}</select></label><label>Início<input type="date" value={form.inicio} onChange={e=>setForm({...form,inicio:e.target.value})} required/></label><label className="checkbox"><input type="checkbox" checked={form.responsavel} onChange={e=>setForm({...form,responsavel:e.target.checked})}/> Responsável pela unidade</label></div><div className="dialog-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary">Vincular</button></div></form></DialogPanel></div></Dialog>}
